# Site tests: builds the Jekyll site once, then checks structure, blog and links.
# Run with:  bundle exec ruby test/site_test.rb
require "minitest/autorun"
require "yaml"
require "uri"
require "tmpdir"
require "open3"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
CONFIG = YAML.load_file(File.join(ROOT, "_config.yml"))
BASEURL = CONFIG["baseurl"].to_s
DEST = Dir.mktmpdir("site-test")
BUILD_OUT, BUILD_STATUS = Open3.capture2e("bundle", "exec", "jekyll", "build", "-d", DEST, chdir: ROOT)
Minitest.after_run { FileUtils.remove_entry(DEST) if File.exist?(DEST) }

POSTS = Dir[File.join(ROOT, "_posts", "*.{md,markdown}")].sort.map do |path|
  raw = File.read(path, encoding: "utf-8")
  front = YAML.safe_load(raw[/\A---\n(.*?)\n---/m, 1], permitted_classes: [Time, Date])
  slug = File.basename(path).sub(/\.(md|markdown)\z/, "")
  { path: path, raw: raw, front: front, dir: slug }
end

def page(rel)
  File.read(File.join(DEST, rel), encoding: "utf-8")
end

def html_pages
  ["index.html", "blog/index.html", "about/index.html"] + POSTS.map { |p| "#{p[:dir]}/index.html" }
end

class BuildTest < Minitest::Test
  def test_build_succeeds
    assert BUILD_STATUS.success?, BUILD_OUT
  end

  def test_expected_pages_exist
    html_pages.each { |f| assert File.exist?(File.join(DEST, f)), "missing #{f}" }
    assert File.exist?(File.join(DEST, "404.html"))
    assert File.exist?(File.join(DEST, "css/style.css"))
  end

  def test_feed_is_generated
    feeds = Dir[File.join(DEST, "{feed,index}.xml")]
    refute_empty feeds, "no RSS/Atom feed generated by jekyll-feed"
  end

  def test_site_output_is_not_tracked
    tracked, = Open3.capture2("git", "ls-files", "_site", chdir: ROOT)
    assert_empty tracked.strip, "_site/ should not be tracked"
  end
end

class LayoutTest < Minitest::Test
  def test_single_nav_footer_and_menu_per_page
    html_pages.each do |f|
      html = page(f)
      next if f == "about/index.html" && !html.include?('id="header"') # theme "page" layout
      assert_equal 1, html.scan('id="header"').size, "#{f}: header count"
      assert_equal 1, html.scan('id="sidemenu"').size, "#{f}: sidemenu count"
      assert_equal 1, html.scan("<footer").size, "#{f}: footer count"
      assert_equal 1, html.scan("function openmenu").size, "#{f}: menu script count"
    end
  end

  def test_nav_anchors_exist_on_home_page
    home = page("index.html")
    nav = home[/<ul id="sidemenu">.*?<\/ul>/m]
    anchors = nav.scan(/href="[^"]*?\/#([^"]+)"/).flatten
    refute_empty anchors
    anchors.each { |a| assert_includes home, %(id="#{a}"), "nav link ##{a} has no target" }
  end

  def test_home_sections_present
    home = page("index.html")
    %w[about services mywork].each { |id| assert_equal 1, home.scan(%(id="#{id}")).size, id }
  end

  def test_no_stray_backslash_quotes
    html_pages.each { |f| refute_match(/(href|src|target|rel)="[^"]*\\"/, page(f), f) }
  end
end

class BlogTest < Minitest::Test
  def test_posts_exist
    assert POSTS.size >= 3
  end

  def test_post_front_matter
    POSTS.each do |p|
      %w[layout title date excerpt].each { |k| refute_nil p[:front][k], "#{p[:dir]} missing #{k}" }
      assert_equal "post", p[:front]["layout"]
    end
  end

  def test_blog_index_lists_every_post
    index = page("blog/index.html")
    POSTS.each do |p|
      assert_includes index, %(href="#{BASEURL}/#{p[:dir]}/"), "#{p[:dir]} not linked"
      assert_includes index, p[:front]["title"]
    end
  end

  def test_post_pages_render_title_date_and_back_link
    POSTS.each do |p|
      html = page("#{p[:dir]}/index.html")
      assert_includes html, "<h1>#{p[:front]["title"]}</h1>"
      assert_match(/Published on: \d{1,2} \w{3} \d{4}/, html)
      assert_includes html, %(href="#{BASEURL}/blog" class="back-to-blog")
    end
  end

  def test_each_post_has_one_working_source_link
    POSTS.each do |p|
      html = page("#{p[:dir]}/index.html")
      links = html[/<div id="blog-content">.*?<\/div>/m].scan(/<a href="(https?:[^"]+)"/).flatten
      assert_equal 1, links.size, "#{p[:dir]} source links: #{links}"
      URI.parse(links.first)
    end
  end

  def test_early_work_post
    post = POSTS.find { |p| p[:dir].end_with?("Early-Work") }
    refute_nil post
    html = page("#{post[:dir]}/index.html")
    assert_equal "Early work", post[:front]["title"]
    assert_includes html, "fear of making something lame"
    assert_includes html.tr("’", "'"), "They're too frightened even to start."  # kramdown smartens quotes
    assert_includes html, %(<a href="https://www.paulgraham.com/early.html" target="_blank" rel="noopener noreferrer">Paul Graham</a>)
  end

  def test_posts_newest_first_on_index
    index = page("blog/index.html")
    order = index.scan(%r{href="#{Regexp.escape(BASEURL)}/(\d{4}-\d{2}-\d{2})-}).flatten
    assert_equal order.sort.reverse, order
  end
end

class LinkTest < Minitest::Test
  def local_targets(html)
    html.scan(/(?:href|src)="(#{Regexp.escape(BASEURL)}[^"]*)"/).flatten
  end

  def resolves?(url)
    path = URI.decode_www_form_component(url.sub(/[#?].*/, "").sub(BASEURL, "").gsub("+", "%2B"))
    path = "/" if path.empty?
    full = File.join(DEST, path)
    File.file?(full) || File.file?(File.join(full, "index.html"))
  end

  def test_all_local_links_and_assets_resolve
    broken = []
    html_pages.each do |f|
      local_targets(page(f)).uniq.each { |u| broken << "#{f}: #{u}" unless resolves?(u) }
    end
    assert_empty broken, "broken local references:\n#{broken.join("\n")}"
  end

  def test_external_links_open_safely
    html_pages.each do |f|
      page(f).scan(/<a [^>]*href="https?:[^>]*>/).each do |tag|
        next unless tag.include?('target="_blank"')
        assert_match(/rel="[^"]*noopener/, tag, "#{f}: #{tag}")
      end
    end
  end
end
