title: Brian Kibet Portfolio
email: bryankibet77@gmail.com
description: >-
  A portfolio showcasing my work, skills, and thoughts - some structured, some spontaneous, some random.
baseurl: "/KibetArapKoech.github.io"
url: "https://bryanarapkoech.github.io"
twitter_username: Kibet_ArapKoech
github_username: BryanArapKoech

permalink: /:year-:month-:day-:title/
defaults:
  - scope:
      path: ""
    values:
      permalink: /:path/
  - scope:
      path: "blog"
    values:
      permalink: /blog/
  - scope:
      path: "_posts"
    values:
      permalink: /:year-:month-:day-:title/

theme: minima
plugins:
  - jekyll-feed
